---
abstract: 'Run JavaScript in Safari on Mac OS X'
author:
  - 'Written by Mark Fowler <mark@twoshortplanks.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mac-Safari-JavaScript
no_index:
  directory:
    - inc
    - t
requires:
  JSON::XS: 2.3
  Mac::AppleScript: 0.04
  Test::More: 0
  perl: 5.8.0
resources:
  homepage: http://github.com/2shortplanks/Mac-Safari-JavaScript/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/2shortplanks/Mac-Safari-JavaScript.git
version: 1.04
